[Targets.my_library]
Type = "static"
Srcs = ["example_srcs/lib.c"]
Hdrs = ["example_srcs/lib.h"]

[Targets.my_binary]
Type = "binary"
Srcs = ["example_srcs/main.c"]
Deps = ["my_library"]

[Targets.my_binary_with_glew]
Type = "binary"
Srcs = ["example_srcs/main.c"]
Deps = ["my_library", "glew"]


[Targets.glew]
Type = "external"
Git = "https://github.com/edoren/glew.git"
Hash = "5b995cab14f97231b48bc86b447be5e23b899626"
Config = "make"